import React,{useEffect,useState} from 'react';import {Link} from 'react-router-dom';import {ArrowUpRight,LockKeyhole,Plus,Save,Trash2,Upload} from 'lucide-react';import {api,authHeaders} from '../api/client';
const safeText=v=>v==null?'':String(v); const arr=v=>Array.isArray(v)?v:[];
export default function AdminPage({data,onRefresh}){const [token,setToken]=useState(localStorage.getItem('portfolio_token')||''),[logged,setLogged]=useState(!!localStorage.getItem('portfolio_token')),[tab,setTab]=useState('projects'),[draft,setDraft]=useState(null),[message,setMessage]=useState(''),[guests,setGuests]=useState([]),[guestLoading,setGuestLoading]=useState(false);
 const login=async e=>{e.preventDefault();try{const r=await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:e.target.username.value,password:e.target.password.value})});localStorage.setItem('portfolio_token',r.token);setToken(r.token);setLogged(true);setMessage('Welcome to the cockpit.')}catch(err){setMessage(err.message)}};
 const logout=()=>{localStorage.removeItem('portfolio_token');setToken('');setLogged(false)};
 const loadGuests=async()=>{setGuestLoading(true);try{const rows=await api('/api/admin/guestbook',{headers:authHeaders()});setGuests(Array.isArray(rows)?rows:[])}catch(err){setMessage(err.message)}finally{setGuestLoading(false)}};
 useEffect(()=>{if(logged&&tab==='guestbook')loadGuests()},[logged,tab]);
 const save=async(type,payload)=>{try{const id=payload?._id||payload?.id;let url=`/api/admin/${type}`;let method='POST';if(type==='profile'){url='/api/admin/profile';method='PUT'}else if(id){url+=`/${encodeURIComponent(id)}`;method='PUT'}await api(url,{method,headers:{...authHeaders(),Authorization:`Bearer ${token}`},body:JSON.stringify(payload)});setDraft(null);setMessage('Saved successfully ✦');await onRefresh()}catch(err){setMessage(err.message)}};
 const del=async(type,id)=>{if(!id)return;if(!window.confirm('Delete this item?'))return;try{await api(`/api/admin/${type}/${encodeURIComponent(id)}`,{method:'DELETE',headers:{...authHeaders(),Authorization:`Bearer ${token}`}});setMessage('Deleted.');await onRefresh()}catch(err){setMessage(err.message)}};
 const upload=async(projectId,files)=>{if(!projectId||!files?.length)return;const fd=new FormData();for(const f of files)fd.append('images',f);try{const updated=await api(`/api/admin/projects/${encodeURIComponent(projectId)}/screenshots`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:fd});setDraft(updated);setMessage('Screenshots uploaded ✦ Now describe each image below.');await onRefresh()}catch(err){setMessage(err.message)}};
 if(!logged)return <main className="admin-login"><div className="login-card"><div className="login-symbol"><LockKeyhole/></div><p className="eyebrow">PRIVATE PORTFOLIO COCKPIT</p><h1>Control the <em>world.</em></h1><p>Add projects, upload screenshots, edit skills, experience and profile content without touching code.</p><form onSubmit={login}><input name="username" placeholder="Admin username" required/><input name="password" type="password" placeholder="Password" required/><button>ENTER COCKPIT <ArrowUpRight size={17}/></button></form><small>{message}</small><Link to="/">← Return to portfolio</Link></div></main>;
 return <main className="admin-page"><div className="admin-top"><div><p className="eyebrow">PRIVATE / ADMIN</p><h1>Portfolio <em>cockpit.</em></h1></div><div className="admin-actions"><Link to="/">View site ↗</Link><button onClick={logout}>Logout</button></div></div><div className="admin-layout"><aside><button className={tab==='projects'?'active':''} onClick={()=>{setTab('projects');setDraft(null)}}>Projects</button><button className={tab==='skills'?'active':''} onClick={()=>{setTab('skills');setDraft(null)}}>Skills</button><button className={tab==='experience'?'active':''} onClick={()=>{setTab('experience');setDraft(null)}}>Experience</button><button className={tab==='profile'?'active':''} onClick={()=>{setTab('profile');setDraft(null)}}>Profile</button><button className={tab==='guestbook'?'active':''} onClick={()=>{setTab('guestbook');setDraft(null)}}>Guestbook</button></aside><section className="admin-content"><div className="admin-message">{message}</div>{tab==='projects'&&<ProjectsAdmin data={data} draft={draft} setDraft={setDraft} save={save} del={del} upload={upload}/>} {tab==='skills'&&<CollectionAdmin title="Skills" items={data.skills} fields={['name','category','level','description']} draft={draft} setDraft={setDraft} save={save} del={del} type="skills"/>}{tab==='experience'&&<CollectionAdmin title="Experience" items={data.experience} fields={['company','role','start','end','location','description']} draft={draft} setDraft={setDraft} save={save} del={del} type="experience"/>}{tab==='profile'&&<ProfileEditor data={data.profile} save={save}/>} {tab==='guestbook'&&<GuestbookAdmin guests={guests} loading={guestLoading} refresh={loadGuests}/>}</section></div></main>}
function ProjectsAdmin({data,draft,setDraft,save,del,upload}){const fresh={id:null,no:String(data.projects.length+1).padStart(2,'0'),title:'',slug:'',type:'FULL STACK PROJECT',status:'IN PROGRESS',year:String(new Date().getFullYear()),accent:'mint',summary:'',description:'',tech:[],features:[],coverImage:'',screenshots:[],github:'#',live:'#'};return <><div className="admin-heading"><div><span>CASE STUDIES</span><h2>Projects</h2></div><button onClick={()=>setDraft(fresh)}><Plus/> Add project</button></div>{data.projects.filter(Boolean).map(p=><article className="admin-row" key={p.id}><div className="admin-row-main"><span className="row-no">{p.no}</span><div><b>{p.title||'Untitled project'}</b><small>{p.year||'—'} · {arr(p.tech).join(' · ')}</small></div></div><div className="row-actions"><button onClick={()=>setDraft({...p})}>Edit</button><button onClick={()=>del('projects',p.id)}><Trash2 size={15}/></button></div>{draft?.id===p.id&&<ProjectEditor draft={draft} setDraft={setDraft} save={save} upload={upload}/>}</article>)}{draft?.id===null&&<ProjectEditor draft={draft} setDraft={setDraft} save={save} upload={upload}/>}</>}
function ProjectEditor({draft,setDraft,save,upload}){
 const change=(k,v)=>setDraft(d=>({...d,[k]:v}));
 const shots=arr(draft.screenshots).map((s)=>typeof s==='string'?{image:s,title:'',description:''}:s).filter(s=>s?.image);
 const updateShot=(i,k,v)=>setDraft(d=>({...d,screenshots:arr(d.screenshots).map((s,j)=>j===i?{...(typeof s==='string'?{image:s}:s),[k]:v}:s)}));
 return <div className="editor">
  <div className="field-grid">
   <label>Title<input value={safeText(draft.title)} onChange={e=>change('title',e.target.value)}/></label><label>Slug<input value={safeText(draft.slug)} onChange={e=>change('slug',e.target.value)}/></label><label>Year<input value={safeText(draft.year)} onChange={e=>change('year',e.target.value)}/></label><label>Type<input value={safeText(draft.type)} onChange={e=>change('type',e.target.value)}/></label><label>Status<input value={safeText(draft.status)} onChange={e=>change('status',e.target.value)}/></label><label>Accent<select value={safeText(draft.accent)||'mint'} onChange={e=>change('accent',e.target.value)}><option value="mint">mint</option><option value="peach">peach</option><option value="sky">sky</option></select></label><label className="wide">Summary<input value={safeText(draft.summary)} onChange={e=>change('summary',e.target.value)}/></label><label className="wide">Description<textarea value={safeText(draft.description)} onChange={e=>change('description',e.target.value)}/></label><label className="wide">Tech stack (comma separated)<input value={arr(draft.tech).join(', ')} onChange={e=>change('tech',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label><label className="wide">Features (one per line)<textarea value={arr(draft.features).join('\n')} onChange={e=>change('features',e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))}/></label><label>Live URL<input value={safeText(draft.live)} onChange={e=>change('live',e.target.value)}/></label><label>GitHub URL<input value={safeText(draft.github)} onChange={e=>change('github',e.target.value)}/></label>
  </div>
  <div className="editor-actions"><button onClick={()=>save('projects',draft)}><Save size={15}/> Save project</button>{draft.id&&<label className="upload-btn"><Upload size={15}/> Add project screenshots<input type="file" multiple accept="image/*" onChange={e=>upload(draft.id,e.target.files)}/></label>}</div>
  {shots.length>0&&<div className="screenshot-editor-list">{shots.map((s,i)=><article className="screenshot-editor" key={`${s.image}-${i}`}><div className="screenshot-editor-image"><img src={s.image} alt={s.title||`Screenshot ${i+1}`}/><span>SCREEN {String(i+1).padStart(2,'0')}{i===0?' · COVER':''}</span></div><div className="screenshot-editor-fields"><b>Image {i+1} details</b><label>Section title<input value={safeText(s.title)} placeholder="e.g. Billing dashboard" onChange={e=>updateShot(i,'title',e.target.value)}/></label><label>What did you do here?<textarea value={safeText(s.description)} placeholder="Explain what you built, changed, solved, or implemented in this screen." onChange={e=>updateShot(i,'description',e.target.value)}/></label></div></article>)}</div>}
  <small>First screenshot is automatically used on the main Projects page. Every screenshot gets its own section on the project detail page.</small>
 </div>
}

function CollectionAdmin({title,items,fields,draft,setDraft,save,del,type}){const singular=title.slice(0,-1);return <><div className="admin-heading"><div><span>CONTENT</span><h2>{title}</h2></div><button onClick={()=>setDraft(type==='skills'?{id:null,name:'',category:'Frontend',level:80,description:''}:{id:null,company:'',role:'',start:'',end:'Present',location:'',description:''})}><Plus/> Add {singular}</button></div>{(Array.isArray(items)?items:[]).filter(Boolean).map(x=>{const label=safeText(x.name||x.company||'Untitled');const sub=x.role||x.category||(x.level!=null?`${x.level}%`:'');return <article className="admin-row" key={x.id||label}><div className="admin-row-main"><span className="row-no">✦</span><div><b>{label}</b><small>{sub}</small></div></div><div className="row-actions"><button onClick={()=>setDraft({...x})}>Edit</button><button onClick={()=>del(type,x.id)}><Trash2 size={15}/></button></div>{draft?.id===x.id&&<SimpleEditor draft={draft} setDraft={setDraft} fields={fields} save={save} type={type}/>}</article>})}{draft?.id===null&&<SimpleEditor draft={draft} setDraft={setDraft} fields={fields} save={save} type={type}/>}</>}
function SimpleEditor({draft,setDraft,fields,save,type}){return <div className="editor"><div className="field-grid">{fields.map(f=><label key={f}>{f}<textarea rows={f==='description'?3:1} value={safeText(draft?.[f])} onChange={e=>setDraft(d=>({...d,[f]:f==='level'?Number(e.target.value):e.target.value}))}/></label>)}</div><div className="editor-actions"><button onClick={()=>save(type,draft)}><Save size={15}/> Save</button></div></div>}
function ProfileEditor({data,save}){const [d,setD]=useState({...data});useEffect(()=>setD({...data}),[data]);const keys=['name','role','tagline','about','email','phone','location','github','linkedin','resume'];return <><div className="admin-heading"><div><span>GLOBAL CONTENT</span><h2>Profile</h2></div><button onClick={()=>save('profile',d)}><Save/> Save profile</button></div><div className="editor"><div className="field-grid">{keys.map(k=><label key={k} className={['tagline','about'].includes(k)?'wide':''}>{k}<textarea rows={['tagline','about'].includes(k)?3:1} value={safeText(d[k])} onChange={e=>setD(v=>({...v,[k]:e.target.value}))}/></label>)}</div></div></>}

function GuestbookAdmin({guests,loading,refresh}){return <><div className="admin-heading"><div><span>VISITOR RECORDS</span><h2>Guestbook</h2></div><button onClick={refresh}>Refresh</button></div><div className="guest-admin-list">{loading?<p>Loading visitor records…</p>:guests.length===0?<p>No guestbook entries yet.</p>:guests.map((g,i)=><article className="admin-row guest-admin-row" key={g._id||g.id||i}><div className="admin-row-main"><span className="row-no">{String(i+1).padStart(2,'0')}</span><div><b>{safeText(g.name)||'Anonymous'}</b><small>{safeText(g.contact)||'No contact provided'}</small></div></div><time>{g.createdAt?new Date(g.createdAt).toLocaleString():'—'}</time></article>)}</div></>}
