import mongoose from 'mongoose';import Profile from '../models/Profile.js';import Skill from '../models/Skill.js';import Experience from '../models/Experience.js';import Project from '../models/Project.js';import Certificate from '../models/Certificate.js';import Guestbook from '../models/Guestbook.js';
const db=()=>mongoose.connection.readyState===1;
const unavailable=(res)=>res.status(503).json({message:'MongoDB is not connected'});
export async function portfolio(req,res){if(!db())return unavailable(res);const [profile,skills,experience,projects,certificates]=await Promise.all([Profile.findOne().lean(),Skill.find().sort({createdAt:1}).lean(),Experience.find().sort({createdAt:1}).lean(),Project.find().sort({no:1,createdAt:1}).lean(),Certificate.find().sort({createdAt:-1}).lean()]);res.json({profile:profile||{},skills:skills||[],experience:experience||[],projects:projects||[],certificates:certificates||[]});}
export async function profile(req,res){if(!db())return unavailable(res);res.json(await Profile.findOne().lean()||{});}
export async function skills(req,res){if(!db())return unavailable(res);res.json(await Skill.find().sort({createdAt:1}).lean());}
export async function experience(req,res){if(!db())return unavailable(res);res.json(await Experience.find().sort({createdAt:1}).lean());}
export async function projects(req,res){if(!db())return unavailable(res);res.json(await Project.find().sort({no:1,createdAt:1}).lean());}
export async function projectBySlug(req,res){if(!db())return unavailable(res);const q=mongoose.isValidObjectId(req.params.slug)?{$or:[{slug:req.params.slug},{_id:req.params.slug}]}:{slug:req.params.slug};const p=await Project.findOne(q).lean();if(!p)return res.status(404).json({message:'Project not found'});res.json(p);}
export async function guestbook(req,res){if(!db())return unavailable(res);const name=String(req.body?.name||'').trim(),contact=String(req.body?.contact||'').trim();if(!name)return res.status(400).json({message:'Name is required'});if(contact.length>120)return res.status(400).json({message:'Contact is too long'});await Guestbook.create({name,contact});res.status(201).json({message:'Signed successfully'});}
export async function guestbookList(req,res){if(!db())return unavailable(res);res.json(await Guestbook.find().sort({createdAt:-1}).lean());}
